// -*- C++ -*-
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.2a_p18
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.cs.wustl.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// d:\opendds-3.14\opendds-3.14\ace_wrappers\tao\tao_idl\be\be_codegen.cpp:152

#ifndef _TAO_IDL_DDS_DEMOC_SIDRT9_H_
#define _TAO_IDL_DDS_DEMOC_SIDRT9_H_

#include /**/ "ace/pre.h"


#include /**/ "ace/config-all.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


#include "tao/ORB.h"
#include "tao/Basic_Types.h"
#include "tao/VarOut_T.h"
#include "tao/Arg_Traits_T.h"
#include "tao/Basic_Arguments.h"
#include "tao/Special_Basic_Arguments.h"
#include "tao/Any_Insert_Policy_T.h"
#include "tao/Fixed_Size_Argument_T.h"
#include "tao/Var_Size_Argument_T.h"
#include /**/ "tao/Version.h"
#include /**/ "tao/Versioned_Namespace.h"

#if TAO_MAJOR_VERSION != 2 || TAO_MINOR_VERSION != 2 || TAO_BETA_VERSION != 0
#error This file should be regenerated with TAO_IDL
#endif

#if defined (TAO_EXPORT_MACRO)
#undef TAO_EXPORT_MACRO
#endif
#define TAO_EXPORT_MACRO 

// TAO_IDL - Generated from
// d:\opendds-3.14\opendds-3.14\ace_wrappers\tao\tao_idl\be\be_visitor_module\module_ch.cpp:38

namespace demo
{

  // TAO_IDL - Generated from
  // d:\opendds-3.14\opendds-3.14\ace_wrappers\tao\tao_idl\be\be_type.cpp:261

  struct DataType;

  typedef
    ::TAO_Fixed_Var_T<
        DataType
      >
    DataType_var;

  typedef
    DataType &
    DataType_out;

  // TAO_IDL - Generated from
  // d:\opendds-3.14\opendds-3.14\ace_wrappers\tao\tao_idl\be\be_visitor_structure\structure_ch.cpp:51

  struct  DataType
  {

    // TAO_IDL - Generated from
    // d:\opendds-3.14\opendds-3.14\ace_wrappers\tao\tao_idl\be\be_type.cpp:307

    
    typedef DataType_var _var_type;
    typedef DataType_out _out_type;
    
    ::CORBA::Long Handle;
    ::CORBA::Double Timestamp;
  };

// TAO_IDL - Generated from
// d:\opendds-3.14\opendds-3.14\ace_wrappers\tao\tao_idl\be\be_visitor_module\module_ch.cpp:67

} // module demo

// TAO_IDL - Generated from
// d:\opendds-3.14\opendds-3.14\ace_wrappers\tao\tao_idl\be\be_visitor_arg_traits.cpp:68

TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{

  // TAO_IDL - Generated from
  // d:\opendds-3.14\opendds-3.14\ace_wrappers\tao\tao_idl\be\be_visitor_arg_traits.cpp:947

  template<>
  class Arg_Traits< ::demo::DataType>
    : public
        Fixed_Size_Arg_Traits_T<
            ::demo::DataType,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// d:\opendds-3.14\opendds-3.14\ace_wrappers\tao\tao_idl\be\be_visitor_traits.cpp:62

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations.
namespace TAO
{
}
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// d:\opendds-3.14\opendds-3.14\ace_wrappers\tao\tao_idl\be\be_visitor_structure\cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const demo::DataType &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, demo::DataType &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// d:\opendds-3.14\opendds-3.14\ace_wrappers\tao\tao_idl\be\be_codegen.cpp:1703
#if defined (__ACE_INLINE__)
#include "dds_demoC.inl"
#endif /* defined INLINE */

#include /**/ "ace/post.h"

#endif /* ifndef */

