// -*- C++ -*-
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.2a_p18
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.cs.wustl.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// d:\opendds-3.14\opendds-3.14\ace_wrappers\tao\tao_idl\be\be_codegen.cpp:152

#ifndef _TAO_IDL_DDS_DEMOTYPESUPPORTC_937A6S_H_
#define _TAO_IDL_DDS_DEMOTYPESUPPORTC_937A6S_H_

#include /**/ "ace/pre.h"


#include /**/ "ace/config-all.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


#include "tao/ORB.h"
#include "tao/SystemException.h"
#include "tao/Basic_Types.h"
#include "tao/ORB_Constants.h"
#include "dds/DCPS/ZeroCopyInfoSeq_T.h"
#include "dds/DCPS/ZeroCopySeq_T.h"
#include "tao/Object.h"
#include "tao/String_Manager_T.h"
#include "tao/Sequence_T.h"
#include "tao/Objref_VarOut_T.h"
#include "tao/Seq_Var_T.h"
#include "tao/Seq_Out_T.h"
#include "tao/Arg_Traits_T.h"
#include "tao/Basic_Arguments.h"
#include "tao/Special_Basic_Arguments.h"
#include "tao/Any_Insert_Policy_T.h"
#include "tao/Fixed_Size_Argument_T.h"
#include "tao/Var_Size_Argument_T.h"
#include /**/ "tao/Version.h"
#include /**/ "tao/Versioned_Namespace.h"

#include "dds_demoC.h"
#include "dds/DdsDcpsInfrastructureC.h"
#include "dds/DdsDcpsPublicationC.h"
#include "dds/DdsDcpsSubscriptionExtC.h"
#include "dds/DdsDcpsTopicC.h"
#include "dds/DdsDcpsTypeSupportExtC.h"

#if TAO_MAJOR_VERSION != 2 || TAO_MINOR_VERSION != 2 || TAO_BETA_VERSION != 0
#error This file should be regenerated with TAO_IDL
#endif

#if defined (TAO_EXPORT_MACRO)
#undef TAO_EXPORT_MACRO
#endif
#define TAO_EXPORT_MACRO 

// TAO_IDL - Generated from
// d:\opendds-3.14\opendds-3.14\ace_wrappers\tao\tao_idl\be\be_visitor_module\module_ch.cpp:38

namespace demo
{

  // TAO_IDL - Generated from
  // d:\opendds-3.14\opendds-3.14\ace_wrappers\tao\tao_idl\be\be_visitor_sequence\sequence_ch.cpp:102

  typedef ::TAO::DCPS::ZeroCopyDataSeq< demo::DataType, DCPS_ZERO_COPY_SEQ_DEFAULT_SIZE> DataTypeSeq;
  

  // TAO_IDL - Generated from
  // d:\opendds-3.14\opendds-3.14\ace_wrappers\tao\tao_idl\be\be_interface.cpp:751

#if !defined (_DEMO_DATATYPETYPESUPPORT__VAR_OUT_CH_)
#define _DEMO_DATATYPETYPESUPPORT__VAR_OUT_CH_

  class DataTypeTypeSupport;
  typedef DataTypeTypeSupport *DataTypeTypeSupport_ptr;

  typedef
    TAO_Objref_Var_T<
        DataTypeTypeSupport
      >
    DataTypeTypeSupport_var;
  
  typedef
    TAO_Objref_Out_T<
        DataTypeTypeSupport
      >
    DataTypeTypeSupport_out;

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // d:\opendds-3.14\opendds-3.14\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_ch.cpp:43

  class  DataTypeTypeSupport
    : public virtual ::OpenDDS::DCPS::TypeSupport
  
  {
  public:

    // TAO_IDL - Generated from
    // d:\opendds-3.14\opendds-3.14\ace_wrappers\tao\tao_idl\be\be_type.cpp:307

    typedef DataTypeTypeSupport_ptr _ptr_type;
    typedef DataTypeTypeSupport_var _var_type;
    typedef DataTypeTypeSupport_out _out_type;

    // The static operations.
    static DataTypeTypeSupport_ptr _duplicate (DataTypeTypeSupport_ptr obj);

    static void _tao_release (DataTypeTypeSupport_ptr obj);

    static DataTypeTypeSupport_ptr _narrow (::CORBA::Object_ptr obj);
    static DataTypeTypeSupport_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static DataTypeTypeSupport_ptr _nil (void);

    // TAO_IDL - Generated from
    // d:\opendds-3.14\opendds-3.14\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_ch.cpp:140

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    DataTypeTypeSupport (void);

    

    virtual ~DataTypeTypeSupport (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    DataTypeTypeSupport (const DataTypeTypeSupport &);

    void operator= (const DataTypeTypeSupport &);
  };

  // TAO_IDL - Generated from
  // d:\opendds-3.14\opendds-3.14\ace_wrappers\tao\tao_idl\be\be_interface.cpp:751

#if !defined (_DEMO_DATATYPEDATAWRITER__VAR_OUT_CH_)
#define _DEMO_DATATYPEDATAWRITER__VAR_OUT_CH_

  class DataTypeDataWriter;
  typedef DataTypeDataWriter *DataTypeDataWriter_ptr;

  typedef
    TAO_Objref_Var_T<
        DataTypeDataWriter
      >
    DataTypeDataWriter_var;
  
  typedef
    TAO_Objref_Out_T<
        DataTypeDataWriter
      >
    DataTypeDataWriter_out;

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // d:\opendds-3.14\opendds-3.14\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_ch.cpp:43

  class  DataTypeDataWriter
    : public virtual ::DDS::DataWriter
  
  {
  public:

    // TAO_IDL - Generated from
    // d:\opendds-3.14\opendds-3.14\ace_wrappers\tao\tao_idl\be\be_type.cpp:307

    typedef DataTypeDataWriter_ptr _ptr_type;
    typedef DataTypeDataWriter_var _var_type;
    typedef DataTypeDataWriter_out _out_type;

    // The static operations.
    static DataTypeDataWriter_ptr _duplicate (DataTypeDataWriter_ptr obj);

    static void _tao_release (DataTypeDataWriter_ptr obj);

    static DataTypeDataWriter_ptr _narrow (::CORBA::Object_ptr obj);
    static DataTypeDataWriter_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static DataTypeDataWriter_ptr _nil (void);

    virtual ::DDS::InstanceHandle_t register_instance (
      const ::demo::DataType & instance) = 0;

    virtual ::DDS::InstanceHandle_t register_instance_w_timestamp (
      const ::demo::DataType & instance,
      const ::DDS::Time_t & timestamp) = 0;

    virtual ::DDS::ReturnCode_t unregister_instance (
      const ::demo::DataType & instance,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::ReturnCode_t unregister_instance_w_timestamp (
      const ::demo::DataType & instance,
      ::DDS::InstanceHandle_t handle,
      const ::DDS::Time_t & timestamp) = 0;

    virtual ::DDS::ReturnCode_t write (
      const ::demo::DataType & instance_data,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::ReturnCode_t write_w_timestamp (
      const ::demo::DataType & instance_data,
      ::DDS::InstanceHandle_t handle,
      const ::DDS::Time_t & source_timestamp) = 0;

    virtual ::DDS::ReturnCode_t dispose (
      const ::demo::DataType & instance_data,
      ::DDS::InstanceHandle_t instance_handle) = 0;

    virtual ::DDS::ReturnCode_t dispose_w_timestamp (
      const ::demo::DataType & instance_data,
      ::DDS::InstanceHandle_t instance_handle,
      const ::DDS::Time_t & source_timestamp) = 0;

    virtual ::DDS::ReturnCode_t get_key_value (
      ::demo::DataType & key_holder,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::InstanceHandle_t lookup_instance (
      const ::demo::DataType & instance_data) = 0;

    // TAO_IDL - Generated from
    // d:\opendds-3.14\opendds-3.14\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_ch.cpp:140

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    DataTypeDataWriter (void);

    

    virtual ~DataTypeDataWriter (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    DataTypeDataWriter (const DataTypeDataWriter &);

    void operator= (const DataTypeDataWriter &);
  };

  // TAO_IDL - Generated from
  // d:\opendds-3.14\opendds-3.14\ace_wrappers\tao\tao_idl\be\be_interface.cpp:751

#if !defined (_DEMO_DATATYPEDATAREADER__VAR_OUT_CH_)
#define _DEMO_DATATYPEDATAREADER__VAR_OUT_CH_

  class DataTypeDataReader;
  typedef DataTypeDataReader *DataTypeDataReader_ptr;

  typedef
    TAO_Objref_Var_T<
        DataTypeDataReader
      >
    DataTypeDataReader_var;
  
  typedef
    TAO_Objref_Out_T<
        DataTypeDataReader
      >
    DataTypeDataReader_out;

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // d:\opendds-3.14\opendds-3.14\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_ch.cpp:43

  class  DataTypeDataReader
    : public virtual ::OpenDDS::DCPS::DataReaderEx
  
  {
  public:

    // TAO_IDL - Generated from
    // d:\opendds-3.14\opendds-3.14\ace_wrappers\tao\tao_idl\be\be_type.cpp:307

    typedef DataTypeDataReader_ptr _ptr_type;
    typedef DataTypeDataReader_var _var_type;
    typedef DataTypeDataReader_out _out_type;

    // The static operations.
    static DataTypeDataReader_ptr _duplicate (DataTypeDataReader_ptr obj);

    static void _tao_release (DataTypeDataReader_ptr obj);

    static DataTypeDataReader_ptr _narrow (::CORBA::Object_ptr obj);
    static DataTypeDataReader_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static DataTypeDataReader_ptr _nil (void);

    virtual ::DDS::ReturnCode_t read (
      ::demo::DataTypeSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take (
      ::demo::DataTypeSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_w_condition (
      ::demo::DataTypeSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_w_condition (
      ::demo::DataTypeSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t read_next_sample (
      ::demo::DataType & received_data,
      ::DDS::SampleInfo & sample_info) = 0;

    virtual ::DDS::ReturnCode_t take_next_sample (
      ::demo::DataType & received_data,
      ::DDS::SampleInfo & sample_info) = 0;

    virtual ::DDS::ReturnCode_t read_instance (
      ::demo::DataTypeSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take_instance (
      ::demo::DataTypeSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_instance_w_condition (
      ::demo::DataTypeSeq & received_data,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_instance_w_condition (
      ::demo::DataTypeSeq & received_data,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t read_next_instance (
      ::demo::DataTypeSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take_next_instance (
      ::demo::DataTypeSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_next_instance_w_condition (
      ::demo::DataTypeSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t previous_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_next_instance_w_condition (
      ::demo::DataTypeSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t previous_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t return_loan (
      ::demo::DataTypeSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq) = 0;

    virtual ::DDS::ReturnCode_t get_key_value (
      ::demo::DataType & key_holder,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::InstanceHandle_t lookup_instance (
      const ::demo::DataType & instance_data) = 0;

    // TAO_IDL - Generated from
    // d:\opendds-3.14\opendds-3.14\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_ch.cpp:140

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    DataTypeDataReader (void);

    

    virtual ~DataTypeDataReader (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    DataTypeDataReader (const DataTypeDataReader &);

    void operator= (const DataTypeDataReader &);
  };

// TAO_IDL - Generated from
// d:\opendds-3.14\opendds-3.14\ace_wrappers\tao\tao_idl\be\be_visitor_module\module_ch.cpp:67

} // module demo

// TAO_IDL - Generated from
// d:\opendds-3.14\opendds-3.14\ace_wrappers\tao\tao_idl\be\be_visitor_arg_traits.cpp:68

TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// d:\opendds-3.14\opendds-3.14\ace_wrappers\tao\tao_idl\be\be_visitor_traits.cpp:62

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations.
namespace TAO
{

#if !defined (_DEMO_DATATYPETYPESUPPORT__TRAITS_)
#define _DEMO_DATATYPETYPESUPPORT__TRAITS_

  template<>
  struct  Objref_Traits< ::demo::DataTypeTypeSupport>
  {
    static ::demo::DataTypeTypeSupport_ptr duplicate (
        ::demo::DataTypeTypeSupport_ptr p);
    static void release (
        ::demo::DataTypeTypeSupport_ptr p);
    static ::demo::DataTypeTypeSupport_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::demo::DataTypeTypeSupport_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */

#if !defined (_DEMO_DATATYPEDATAWRITER__TRAITS_)
#define _DEMO_DATATYPEDATAWRITER__TRAITS_

  template<>
  struct  Objref_Traits< ::demo::DataTypeDataWriter>
  {
    static ::demo::DataTypeDataWriter_ptr duplicate (
        ::demo::DataTypeDataWriter_ptr p);
    static void release (
        ::demo::DataTypeDataWriter_ptr p);
    static ::demo::DataTypeDataWriter_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::demo::DataTypeDataWriter_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */

#if !defined (_DEMO_DATATYPEDATAREADER__TRAITS_)
#define _DEMO_DATATYPEDATAREADER__TRAITS_

  template<>
  struct  Objref_Traits< ::demo::DataTypeDataReader>
  {
    static ::demo::DataTypeDataReader_ptr duplicate (
        ::demo::DataTypeDataReader_ptr p);
    static void release (
        ::demo::DataTypeDataReader_ptr p);
    static ::demo::DataTypeDataReader_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::demo::DataTypeDataReader_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */
}
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// d:\opendds-3.14\opendds-3.14\ace_wrappers\tao\tao_idl\be\be_codegen.cpp:1703
#if defined (__ACE_INLINE__)
#include "dds_demoTypeSupportC.inl"
#endif /* defined INLINE */

#include /**/ "ace/post.h"

#endif /* ifndef */

