// -*- C++ -*-
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.2a_p18
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.cs.wustl.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// d:\opendds-3.14\opendds-3.14\ace_wrappers\tao\tao_idl\be\be_codegen.cpp:376


#include "dds_demoTypeSupportC.h"
#include "tao/CDR.h"
#include "ace/OS_NS_string.h"

#if !defined (__ACE_INLINE__)
#include "dds_demoTypeSupportC.inl"
#endif /* !defined INLINE */

// TAO_IDL - Generated from
// d:\opendds-3.14\opendds-3.14\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_cs.cpp:51

// Traits specializations for demo::DataTypeTypeSupport.

demo::DataTypeTypeSupport_ptr
TAO::Objref_Traits<demo::DataTypeTypeSupport>::duplicate (
    demo::DataTypeTypeSupport_ptr p)
{
  return demo::DataTypeTypeSupport::_duplicate (p);
}

void
TAO::Objref_Traits<demo::DataTypeTypeSupport>::release (
    demo::DataTypeTypeSupport_ptr p)
{
  ::CORBA::release (p);
}

demo::DataTypeTypeSupport_ptr
TAO::Objref_Traits<demo::DataTypeTypeSupport>::nil (void)
{
  return demo::DataTypeTypeSupport::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<demo::DataTypeTypeSupport>::marshal (
    const demo::DataTypeTypeSupport_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

demo::DataTypeTypeSupport::DataTypeTypeSupport (void)
{}

demo::DataTypeTypeSupport::~DataTypeTypeSupport (void)
{
}

demo::DataTypeTypeSupport_ptr
demo::DataTypeTypeSupport::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return DataTypeTypeSupport::_duplicate (
      dynamic_cast<DataTypeTypeSupport_ptr> (_tao_objref)
    );
}

demo::DataTypeTypeSupport_ptr
demo::DataTypeTypeSupport::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return DataTypeTypeSupport::_duplicate (
      dynamic_cast<DataTypeTypeSupport_ptr> (_tao_objref)
    );
}

demo::DataTypeTypeSupport_ptr
demo::DataTypeTypeSupport::_nil (void)
{
  return 0;
}

demo::DataTypeTypeSupport_ptr
demo::DataTypeTypeSupport::_duplicate (DataTypeTypeSupport_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
demo::DataTypeTypeSupport::_tao_release (DataTypeTypeSupport_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
demo::DataTypeTypeSupport::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/TypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:OpenDDS/DCPS/TypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:demo/DataTypeTypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* demo::DataTypeTypeSupport::_interface_repository_id (void) const
{
  return "IDL:demo/DataTypeTypeSupport:1.0";
}

::CORBA::Boolean
demo::DataTypeTypeSupport::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

// TAO_IDL - Generated from
// d:\opendds-3.14\opendds-3.14\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_cs.cpp:51

// Traits specializations for demo::DataTypeDataWriter.

demo::DataTypeDataWriter_ptr
TAO::Objref_Traits<demo::DataTypeDataWriter>::duplicate (
    demo::DataTypeDataWriter_ptr p)
{
  return demo::DataTypeDataWriter::_duplicate (p);
}

void
TAO::Objref_Traits<demo::DataTypeDataWriter>::release (
    demo::DataTypeDataWriter_ptr p)
{
  ::CORBA::release (p);
}

demo::DataTypeDataWriter_ptr
TAO::Objref_Traits<demo::DataTypeDataWriter>::nil (void)
{
  return demo::DataTypeDataWriter::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<demo::DataTypeDataWriter>::marshal (
    const demo::DataTypeDataWriter_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

demo::DataTypeDataWriter::DataTypeDataWriter (void)
{}

demo::DataTypeDataWriter::~DataTypeDataWriter (void)
{
}

demo::DataTypeDataWriter_ptr
demo::DataTypeDataWriter::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return DataTypeDataWriter::_duplicate (
      dynamic_cast<DataTypeDataWriter_ptr> (_tao_objref)
    );
}

demo::DataTypeDataWriter_ptr
demo::DataTypeDataWriter::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return DataTypeDataWriter::_duplicate (
      dynamic_cast<DataTypeDataWriter_ptr> (_tao_objref)
    );
}

demo::DataTypeDataWriter_ptr
demo::DataTypeDataWriter::_nil (void)
{
  return 0;
}

demo::DataTypeDataWriter_ptr
demo::DataTypeDataWriter::_duplicate (DataTypeDataWriter_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
demo::DataTypeDataWriter::_tao_release (DataTypeDataWriter_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
demo::DataTypeDataWriter::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/Entity:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:DDS/DataWriter:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:demo/DataTypeDataWriter:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* demo::DataTypeDataWriter::_interface_repository_id (void) const
{
  return "IDL:demo/DataTypeDataWriter:1.0";
}

::CORBA::Boolean
demo::DataTypeDataWriter::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

// TAO_IDL - Generated from
// d:\opendds-3.14\opendds-3.14\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_cs.cpp:51

// Traits specializations for demo::DataTypeDataReader.

demo::DataTypeDataReader_ptr
TAO::Objref_Traits<demo::DataTypeDataReader>::duplicate (
    demo::DataTypeDataReader_ptr p)
{
  return demo::DataTypeDataReader::_duplicate (p);
}

void
TAO::Objref_Traits<demo::DataTypeDataReader>::release (
    demo::DataTypeDataReader_ptr p)
{
  ::CORBA::release (p);
}

demo::DataTypeDataReader_ptr
TAO::Objref_Traits<demo::DataTypeDataReader>::nil (void)
{
  return demo::DataTypeDataReader::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<demo::DataTypeDataReader>::marshal (
    const demo::DataTypeDataReader_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

demo::DataTypeDataReader::DataTypeDataReader (void)
{}

demo::DataTypeDataReader::~DataTypeDataReader (void)
{
}

demo::DataTypeDataReader_ptr
demo::DataTypeDataReader::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return DataTypeDataReader::_duplicate (
      dynamic_cast<DataTypeDataReader_ptr> (_tao_objref)
    );
}

demo::DataTypeDataReader_ptr
demo::DataTypeDataReader::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return DataTypeDataReader::_duplicate (
      dynamic_cast<DataTypeDataReader_ptr> (_tao_objref)
    );
}

demo::DataTypeDataReader_ptr
demo::DataTypeDataReader::_nil (void)
{
  return 0;
}

demo::DataTypeDataReader_ptr
demo::DataTypeDataReader::_duplicate (DataTypeDataReader_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
demo::DataTypeDataReader::_tao_release (DataTypeDataReader_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
demo::DataTypeDataReader::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/Entity:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:DDS/DataReader:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:OpenDDS/DCPS/DataReaderEx:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:demo/DataTypeDataReader:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* demo::DataTypeDataReader::_interface_repository_id (void) const
{
  return "IDL:demo/DataTypeDataReader:1.0";
}

::CORBA::Boolean
demo::DataTypeDataReader::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

